// <auto-generated />
namespace BITCollege_Felipe_Rincon.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Data_Annotations_Remove : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Data_Annotations_Remove));
        
        string IMigrationMetadata.Id
        {
            get { return "202402261931304_Data_Annotations_Remove"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
